---
title: "IVAD: A Interactive Visual Analytics Dashboard for Exploring VAST Challenge 2021"
description: |
  The contents in the text analysis and visualization project.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

## 1.Abstract

The 2021 Visual Analytics Science and Technology (VAST) Challenge presented researchers with a single fictitious scenario: the disappearance of staff members of the GASTech oil and gas company on location on the island of Kronos. A group named the Protectors of Kronos (POK) was the prime suspect in the disappearance. Three mini-challenges and a grand challenge were offered. For more information, please see VAST Challenge 2021.

This module will research Mini-Challenge 3 which includes multiple types of text data for participants to feature real-time streaming social media and emergency service data for participants to provide hostage and kidnapper information.This challenge has 3 tasks and questions and asked the participants to integrate results to evaluate the changing levels of risk to the public and recommend actions. The visualization application is created by R shiny as the platform. The insights derived could provide useful information and guides how to identify important messages online, which would helpful for polices to tell useful information and discard unless information. Besides, the evaluation of risk would provide important guided for keeping public security.

# 2. Obejctive

The application uses the free and open-source R language that offers a thriving programming environment for statistical and graphical analysis. Our 4 design considerations for development:

+ Performing calculations/logic within R for reproducibility,

+ Using standard R packages on the Comprehensive R Archive Network(CRAN) for supportability.

+ Using Shiny to webify the codes for simplicity.

+ Providing options and visualizations for interactivity.

## 3.Data Source

Three datasets in Mini-Challenge 3 are provided:

+ Microblog records that have been identified by automated filters as being potentially relevant to the ongoing incident.
+ Text transcripts of emergency dispatches by the Abila, Kronos local police and fire departments.
+ maps of Abila and background documents.

The data of Microblog and text transcripts of emergency dispatches are found in three segments:

+ Segment 1 :“csv-1700-1830.csv” - covers the time period from 1700 to 1830 Abila time on January 23.

+ Segment 2: "csv-1831-2000.csv’- covers the time period from 1830 to 2000 Abila time on January 23.

+ Segment 3: “csv-2001-2131.csv” - covers the time period from 2000 to shortly after 2130 Abila time on January 23.

The number of "Total Message", "Message Blog" and "Call Center" is 4063, 3872 and 191.

## 4.Data Preparation

All data preparations are performed using R. We combined the data of Microblog and text transcripts and convert the date variable to right time format, which is necessary for the following analysis. And based on content of data provided, we classified records into three segments: Junk, Typical_Chatter and Meaningful records.

+ Junk: Referred to advertisements or financial purpose reports.
+ Meaningful: Refers to informative records which spread real news about ongoing or impending events happen in Aliba.
+ Typical Chatter: Represents no meaningful and irrelevant or inappropriate messages post online.


